import { RATES_AS_OF } from '@/lib/tools/currency'
import type { ExportRow } from '@/lib/tools/export'

interface PrintReportProps {
  toolName: string
  toolId: string
  currency: string
  inputs: ExportRow[]
  results: ExportRow[]
}

export default function PrintReport({
  toolName,
  toolId,
  currency,
  inputs,
  results,
}: PrintReportProps) {
  return (
    <div id="print-report" className="hidden print:block p-8 text-black bg-white">
      <div className="border-b-2 border-black pb-4 mb-6">
        <p className="text-xs uppercase tracking-widest text-gray-500 mb-1">SPECTER</p>
        <h1 className="text-2xl font-bold">{toolName}</h1>
        <p className="text-sm text-gray-500 mt-1" suppressHydrationWarning>
          Generated: {new Date().toLocaleDateString()} · Currency: {currency} · Rates
          as of {RATES_AS_OF}
        </p>
      </div>

      <div className="mb-6">
        <h2 className="text-sm font-bold uppercase tracking-wide mb-3">Inputs</h2>
        <table className="w-full text-sm border-collapse">
          <tbody>
            {inputs.map(({ label, value }) => (
              <tr key={label} className="border-b border-gray-200">
                <td className="py-1.5 pr-4 text-gray-600 w-1/2">{label}</td>
                <td className="py-1.5 font-mono font-medium">{value}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mb-8">
        <h2 className="text-sm font-bold uppercase tracking-wide mb-3">Results</h2>
        <table className="w-full text-sm border-collapse">
          <tbody>
            {results.map(({ label, value }) => (
              <tr key={label} className="border-b border-gray-200">
                <td className="py-1.5 pr-4 text-gray-600 w-1/2">{label}</td>
                <td className="py-1.5 font-mono font-bold">{value}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p className="text-xs text-gray-400 border-t border-gray-200 pt-4">
        Generated by SPECTER · specter.app · Free ecommerce tools · {toolId}
      </p>
    </div>
  )
}
